<script def>
{"navigationBarTitleText":"应用测试","description":"Rokid Glasses AIUI 应用层 42 项完整能力基线：运行时、页面环境感知、显示交互、音频AI、视觉、传感器、设备信息、连接、网络、存储与原生层边界。"}
</script>
<script setup>
import { EvidenceState, StateLabels, CapabilityCatalog, createResult, summarizeResults, summaryText, sanitizeMetric, safeDeviceInfo } from '../../lib/catalog.js';
import { withTimeout, extractSpeechResult } from '../../lib/detector.js';
const wait=(ms)=>new Promise((r)=>setTimeout(r,ms));
const result=(state,evidence,metric='')=>({state,evidence,metric:sanitizeMetric(metric)});
export default {
 data:{version:'0.3.1',phase:'idle',headline:'完整设备能力基线 · 未开始',summary:`共 ${CapabilityCatalog.length} 项 · 确认键开始`,pageText:'1/1',visibleResults:[]},
 onLoad(){this.runId=0;this.results=CapabilityCatalog.map((c)=>createResult(c));this.pageIndex=0;this.pageSize=7;this.lastConfirmAt=0;this.resources=[];this.shared={};this.pageTimer=null;this.renderPage();},
 onShow(){this.startPaging();},onHide(){this.stopPaging();},onUnload(){this.stopPaging();this.cancelRun();},
 onVoiceWakeup(){this.shared.voiceWakeup=true;},onHeadGesture(){this.shared.headGesture=true;},onHeadGestureStateChange(){this.shared.headGesture=true;},onOrientationStabilityChange(){this.shared.orientationStability=true;},
 startPaging(){this.stopPaging();this.pageTimer=setInterval(()=>{const p=Math.max(1,Math.ceil(this.results.length/this.pageSize));this.pageIndex=(this.pageIndex+1)%p;this.renderPage();},4000);},
 stopPaging(){if(this.pageTimer)clearInterval(this.pageTimer);this.pageTimer=null;},
 onKeyUp(e){const c=e&&e.code;if(c==='Enter'||c==='GlobalHook'){e.preventDefault();const n=Date.now();if(n-this.lastConfirmAt<1500)return;this.lastConfirmAt=n;this.onConfirm();}else if(c==='Backspace')this.cancelRun();},
 onConfirm(){if(this.data.phase==='running'){this.cancelRun();this.setData({phase:'done',headline:'诊断已停止',summary:summaryText(summarizeResults(this.results))});return;}this.runAll();},
 cancelRun(){this.runId+=1;for(const r of this.resources||[]){try{r.stop?r.stop():r.abort?r.abort():r.close?r.close():null;}catch(e){}}this.resources=[];},
 renderPage(){const p=Math.max(1,Math.ceil(this.results.length/this.pageSize));if(this.pageIndex>=p)this.pageIndex=0;const s=this.pageIndex*this.pageSize;this.setData({visibleResults:this.results.slice(s,s+this.pageSize).map((x)=>({...x,stateLabel:StateLabels[x.state]})),pageText:`${this.pageIndex+1}/${p}`});},
 setResult(id,patch){const i=this.results.findIndex((x)=>x.id===id);if(i<0)return;this.results[i]={...this.results[i],...patch};this.pageIndex=Math.floor(i/this.pageSize);this.renderPage();this.setData({summary:summaryText(summarizeResults(this.results))});},
 async runProbe(cap,rid){this.setResult(cap.id,result(EvidenceState.RUNNING,'执行中'));try{const o=await withTimeout(Promise.resolve(this.executeProbe(cap.id,rid)),16000,cap.id);if(rid===this.runId)this.setResult(cap.id,o||result(EvidenceState.FAILED,'无有效结果'));}catch(e){if(rid===this.runId)this.setResult(cap.id,result(EvidenceState.FAILED,/timed out/i.test(String(e&&e.message))?'执行超时':'调用失败',e&&e.name));}},
 async runAll(){this.cancelRun();const rid=this.runId;this.results=CapabilityCatalog.map((c)=>createResult(c));this.pageIndex=0;this.setData({phase:'running',headline:'完整能力基线 · 执行中',summary:`0/${CapabilityCatalog.length} 已执行`});this.renderPage();for(const c of CapabilityCatalog){if(rid!==this.runId)return;await this.runProbe(c,rid);}if(rid!==this.runId)return;this.setData({phase:'done',headline:'能力基线执行完成',summary:summaryText(summarizeResults(this.results))});},
 async executeProbe(id,rid){switch(id){
 case'runtime.core':{const a=[typeof Promise,typeof fetch,typeof AbortController,typeof crypto,typeof URL],n=a.filter((v)=>v!=='undefined').length;return result(n===a.length?EvidenceState.VERIFIED:EvidenceState.FAILED,'核心对象可调用',`${n}/${a.length}`);}
 case'runtime.streams':{if(typeof ReadableStream==='undefined'||typeof TextDecoder==='undefined')return result(EvidenceState.UNSUPPORTED,'流或解码器未暴露');const d=new TextDecoder().decode(new Uint8Array([65]));return result(d==='A'?EvidenceState.VERIFIED:EvidenceState.FAILED,'字节解码闭环','UTF-8');}
 case'runtime.url':{if(typeof URL==='undefined'||typeof URLSearchParams==='undefined')return result(EvidenceState.UNSUPPORTED,'无URL解析接口');const u=new URL('https://example.com/?a=1');return result(u.searchParams.get('a')==='1'?EvidenceState.VERIFIED:EvidenceState.FAILED,'URL与参数解析闭环','HTTPS');}
 case'runtime.performance':{const s=typeof performance!=='undefined'&&performance.now?performance.now():Date.now();await wait(20);const e=(typeof performance!=='undefined'&&performance.now?performance.now():Date.now())-s;return result(e>=0?EvidenceState.VERIFIED:EvidenceState.FAILED,'单调时钟推进',`${Math.round(e)} ms`);}
 case'display.viewport':{const w=typeof screen!=='undefined'?screen.width:0,h=typeof screen!=='undefined'?screen.height:0;return result(w&&h?EvidenceState.VERIFIED:EvidenceState.SURFACE,'读取显示视口',w&&h?`${w}×${h}`:'480×352布局');}
 case'display.canvas':return this.probeCanvas();
 case'input.confirm':return result(EvidenceState.VERIFIED,'本次运行由确认键触发','已去重');case'lifecycle.page':return result(EvidenceState.VERIFIED,'onLoad/onShow已执行','页面存活');
 case'page.world':return this.probeWorldAwareness();case'page.headgesture':return result(this.shared.headGesture?EvidenceState.VERIFIED:typeof this.enableWorldAwareness==='function'?EvidenceState.NOT_RUN:EvidenceState.UNSUPPORTED,this.shared.headGesture?'已收到头部手势事件':'需用户真实头部动作验证');case'page.voicewakeup':return result(this.shared.voiceWakeup?EvidenceState.VERIFIED:EvidenceState.NOT_RUN,this.shared.voiceWakeup?'本次已收到语音唤醒事件':'需从系统语音唤醒进入');
 case'speech.mic':return this.probeSpeech();case'speech.session':return this.probeSpeechSession();
 case'audio.synthesis':return this.probeSynthesis();case'audio.webaudio':return this.probeWebAudio();case'audio.player':return result(typeof SpeechAudioPlayer!=='undefined'||typeof Audio!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNSUPPORTED,'播放器入口；无测试音源');
 case'ai.language':if(typeof LanguageModel==='undefined')return result(EvidenceState.UNSUPPORTED,'无LanguageModel入口');return typeof LanguageModel.availability==='function'?result(EvidenceState.VERIFIED,'availability真实返回',String(await LanguageModel.availability())):result(EvidenceState.SURFACE,'模型构造器存在');
 case'camera.live':return this.probeCamera(rid);case'camera.imagecapture':return this.shared.imageCapture||result(typeof ImageCapture!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNSUPPORTED,'ImageCapture入口检查');case'camera.devices':return this.probeMediaDevices();case'camera.recorder':return result(typeof MediaRecorder!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNSUPPORTED,'录制接口存在；不保存媒体');
 case'vision.barcode':if(typeof BarcodeDetector==='undefined')return result(EvidenceState.UNSUPPORTED,'无BarcodeDetector');return result(EvidenceState.VERIFIED,'支持格式真实返回',`${(await BarcodeDetector.getSupportedFormats()).length} formats`);
 case'sensor.accelerometer':return this.probeSensor('Accelerometer','三轴加速度');case'sensor.gyroscope':return this.probeSensor('Gyroscope','三轴角速度');case'sensor.orientation':return this.probeSensor('AbsoluteOrientationSensor','四元数姿态');case'sensor.magnetometer':return result(typeof Magnetometer!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNAVAILABLE,'仅官方示例存在，无API契约');
 case'device.battery':if(typeof navigator==='undefined'||typeof navigator.getBattery!=='function')return result(EvidenceState.UNSUPPORTED,'无BatteryManager入口');{const b=await navigator.getBattery();return result(EvidenceState.VERIFIED,'电池状态真实返回',`${Math.round(b.level*100)}% · ${b.charging?'充电':'放电'}`);}
 case'device.info':{const i=safeDeviceInfo(typeof navigator!=='undefined'?navigator:{},typeof screen!=='undefined'?screen:{});return result(EvidenceState.VERIFIED,'仅非敏感环境字段',`${i.platform||'平台未知'} · ${i.language||'语言未知'}`);}
 case'geo.position':return this.probeGeolocation();case'bluetooth.availability':if(typeof navigator==='undefined'||!navigator.bluetooth)return result(EvidenceState.UNSUPPORTED,'无navigator.bluetooth');return typeof navigator.bluetooth.getAvailability==='function'?result(EvidenceState.VERIFIED,'蓝牙可用性真实返回',(await navigator.bluetooth.getAvailability())?'available':'unavailable'):result(EvidenceState.SURFACE,'蓝牙对象存在');
 case'bluetooth.device':return result(EvidenceState.NOT_RUN,'需要用户选择真实BLE外设');case'network.https':return this.probeHttps();case'network.wxhttps':return this.probeWxHttps();case'network.websocket':return result(typeof WebSocket!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNSUPPORTED,'无回显服务，不连接');case'network.sse':return result(typeof EventSource!=='undefined'?EvidenceState.SURFACE:EvidenceState.UNSUPPORTED,'无SSE服务，不连接');case'network.mobileproxy':return result(EvidenceState.NOT_RUN,'需断Wi-Fi与手机网络A/B验证');
 case'storage.local':return this.probeLocalStorage();case'storage.wx':return this.probeWxStorage();case'storage.manager':return this.probeStorageManager();case'storage.opfs':return this.probeOpfs();
 case'native.cxrs':return result(EvidenceState.UNAVAILABLE,'属于CXR-S/Native层');case'system.private':return result(EvidenceState.UNAVAILABLE,'AIUI无公开安全接口');default:return result(EvidenceState.NOT_RUN,'未注册执行器');}},
 probeSpeech(){return new Promise((resolve)=>{const C=typeof SpeechRecognition!=='undefined'?SpeechRecognition:typeof webkitSpeechRecognition!=='undefined'?webkitSpeechRecognition:null;if(!C){resolve(result(EvidenceState.UNSUPPORTED,'无SpeechRecognition'));return;}const r=new C();this.resources.push(r);let done=false;const f=(v)=>{if(done)return;done=true;try{r.abort();}catch(e){}resolve(v);};r.lang='zh-CN';r.interimResults=true;r.continuous=false;r.onresult=(e)=>{const o=extractSpeechResult(e);if(o.final&&o.text)f(result(EvidenceState.VERIFIED,'取得非空最终结果','zh-CN final'));};r.onerror=(e)=>f(result(EvidenceState.FAILED,'识别错误',e&&e.error));r.onend=()=>f(result(EvidenceState.FAILED,'结束但无最终结果'));try{r.start();}catch(e){f(result(EvidenceState.FAILED,'识别启动失败',e.name));}setTimeout(()=>f(result(EvidenceState.FAILED,'识别超时')),12000);});},
 async probeSpeechSession(){if(typeof SpeechRecognitionSession==='undefined')return result(EvidenceState.UNSUPPORTED,'无SpeechRecognitionSession');try{const s=new SpeechRecognitionSession();const c=typeof s.getCapabilities==='function'?await s.getCapabilities():null;try{s.abort&&s.abort();}catch(e){}return result(c?EvidenceState.VERIFIED:EvidenceState.SURFACE,c?'能力描述真实返回':'Session构造器存在',c&&c.maxChunkBytes?`chunk ${c.maxChunkBytes}B`:'');}catch(e){return result(EvidenceState.FAILED,'Session能力查询失败',e.name);}},
 probeSynthesis(){return new Promise((resolve)=>{if(typeof speechSynthesis==='undefined'||typeof SpeechSynthesisUtterance==='undefined'){resolve(result(EvidenceState.UNSUPPORTED,'无语音合成入口'));return;}const u=new SpeechSynthesisUtterance('音频输出测试');let done=false;const f=(v)=>{if(done)return;done=true;resolve(v);};u.onend=()=>f(result(EvidenceState.VERIFIED,'播放完成事件返回','可听测试音'));u.onerror=(e)=>f(result(EvidenceState.FAILED,'播放失败',e&&e.error));try{speechSynthesis.speak(u,'immediate');}catch(e){f(result(EvidenceState.FAILED,'speak调用失败',e.name));return;}setTimeout(()=>f(result(EvidenceState.SURFACE,'已触发但无完成事件','请听感确认')),7000);});},
 async probeWebAudio(){const C=typeof AudioContext!=='undefined'?AudioContext:typeof webkitAudioContext!=='undefined'?webkitAudioContext:null;if(!C)return result(EvidenceState.UNSUPPORTED,'无Web Audio入口');const c=new C();this.resources.push(c);const o=c.createOscillator(),g=c.createGain();g.gain.value=0;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.02);await wait(50);try{await c.close();}catch(e){}return result(EvidenceState.VERIFIED,'静音振荡器处理闭环',c.sampleRate?`${c.sampleRate} Hz`:'已处理');},
 probeCanvas(){try{if(typeof Canvas==='undefined')return result(EvidenceState.SURFACE,'需绑定页面canvas验证');const c=new Canvas(2,2),x=c.getContext('2d');x.fillStyle='#40ff5e';x.fillRect(0,0,1,1);const p=x.getImageData(0,0,1,1).data;return result(p[1]>0?EvidenceState.VERIFIED:EvidenceState.FAILED,'Canvas像素闭环','2×2');}catch(e){return result(EvidenceState.FAILED,'Canvas绘制失败',e.name);}},
 async probeWorldAwareness(){if(typeof this.enableWorldAwareness!=='function')return result(EvidenceState.UNSUPPORTED,'无环境感知页面API');try{await Promise.resolve(this.enableWorldAwareness({mode:'normal'}));this.resources.push({stop:()=>this.disableWorldAwareness&&this.disableWorldAwareness()});return result(this.orientationSensor?EvidenceState.VERIFIED:EvidenceState.SURFACE,this.orientationSensor?'页面姿态传感器已挂载':'环境感知已启用，等待姿态','normal');}catch(e){return result(EvidenceState.FAILED,'环境感知启用失败',e.name);}},
 async probeCamera(rid){if(typeof navigator==='undefined'||!navigator.mediaDevices||typeof navigator.mediaDevices.getUserMedia!=='function')return result(EvidenceState.UNSUPPORTED,'无getUserMedia');const s=await withTimeout(navigator.mediaDevices.getUserMedia({video:true}),12000,'camera');if(rid!==this.runId){for(const t of s.getTracks())t.stop();return result(EvidenceState.NOT_RUN,'运行取消');}const t=s.getVideoTracks()[0],live=!!(t&&t.readyState==='live'),x=live&&t.getSettings?t.getSettings():{};this.shared.imageCapture=typeof ImageCapture!=='undefined'&&t?result(EvidenceState.VERIFIED,'已绑定真实视频轨'):result(EvidenceState.UNSUPPORTED,'无ImageCapture');for(const q of s.getTracks())q.stop();return result(live?EvidenceState.VERIFIED:EvidenceState.FAILED,live?'取得实时视频轨':'未取得实时视频轨',live?`${x.width||'?'}×${x.height||'?'}`:'');},
 async probeMediaDevices(){if(typeof navigator==='undefined'||!navigator.mediaDevices)return result(EvidenceState.UNSUPPORTED,'无mediaDevices');if(typeof navigator.mediaDevices.enumerateDevices!=='function')return result(EvidenceState.SURFACE,'mediaDevices存在，无枚举接口');const ds=await navigator.mediaDevices.enumerateDevices();const counts={};for(const d of ds)counts[d.kind]=(counts[d.kind]||0)+1;return result(EvidenceState.VERIFIED,'媒体设备类别已枚举',Object.entries(counts).map(([k,v])=>`${k}:${v}`).join(' '));},
 probeSensor(name,evidence){return new Promise((resolve)=>{const C=globalThis[name];if(typeof C==='undefined'){resolve(result(EvidenceState.UNSUPPORTED,`无${name}`));return;}let s,done=false;const f=(v)=>{if(done)return;done=true;try{s.stop();}catch(e){}resolve(v);};try{s=new C({frequency:30});this.resources.push(s);}catch(e){f(result(EvidenceState.FAILED,'传感器构造失败',e.name));return;}s.addEventListener('reading',()=>{const ok=name==='AbsoluteOrientationSensor'?s.quaternion&&s.quaternion.length===4:[s.x,s.y,s.z].every(Number.isFinite);if(ok)f(result(EvidenceState.VERIFIED,`${evidence}有效读数`,s.timestamp?'timestamp OK':'sample OK'));});s.addEventListener('error',(e)=>f(result(EvidenceState.FAILED,'传感器错误',e&&e.error)));try{s.start();}catch(e){f(result(EvidenceState.FAILED,'传感器启动失败',e.name));}setTimeout(()=>f(result(EvidenceState.FAILED,'传感器采样超时')),5000);});},
 probeGeolocation(){return new Promise((resolve)=>{if(typeof navigator==='undefined'||!navigator.geolocation){resolve(result(EvidenceState.UNSUPPORTED,'无Geolocation'));return;}navigator.geolocation.getCurrentPosition((p)=>resolve(result(EvidenceState.VERIFIED,'取得位置但不显示坐标',p.coords&&Number.isFinite(p.coords.accuracy)?`精度约${Math.round(p.coords.accuracy)}m`:'位置有效')),(e)=>resolve(result(EvidenceState.FAILED,'定位失败',`code ${e&&e.code}`)),{enableHighAccuracy:false,timeout:8000,maximumAge:0});});},
 async probeHttps(){const s=Date.now(),r=await withTimeout(fetch('https://js.rokid.com/'),8000,'https'),ok=r&&r.status>=200&&r.status<300;return result(ok?EvidenceState.VERIFIED:EvidenceState.FAILED,ok?'公网请求返回2xx':'公网非2xx',`HTTP ${r.status} · ${Date.now()-s}ms`);},
 probeWxHttps(){return new Promise((resolve)=>{if(typeof wx==='undefined'||typeof wx.request!=='function'){resolve(result(EvidenceState.UNSUPPORTED,'无wx.request'));return;}const s=Date.now();let done=false;const f=(v)=>{if(done)return;done=true;resolve(v);};const task=wx.request({url:'https://js.rokid.com/',method:'HEAD',timeout:8000,success:(r)=>f(result(r.statusCode>=200&&r.statusCode<300?EvidenceState.VERIFIED:EvidenceState.FAILED,'wx.request返回状态',`HTTP ${r.statusCode} · ${Date.now()-s}ms`)),fail:(e)=>f(result(EvidenceState.FAILED,'wx.request失败',e&&e.errMsg))});this.resources.push(task);setTimeout(()=>{try{task&&task.abort&&task.abort();}catch(e){}f(result(EvidenceState.FAILED,'wx.request超时'));},8500);});},
 probeLocalStorage(){if(typeof localStorage==='undefined')return result(EvidenceState.UNSUPPORTED,'无localStorage');const k='__aiui_diag__';localStorage.setItem(k,'1');const ok=localStorage.getItem(k)==='1';localStorage.removeItem(k);return result(ok?EvidenceState.VERIFIED:EvidenceState.FAILED,'临时写读删闭环');},
 probeWxStorage(){if(typeof wx==='undefined'||typeof wx.setStorageSync!=='function')return result(EvidenceState.UNSUPPORTED,'无wx Storage');const k='__aiui_diag__';wx.setStorageSync(k,'1');const ok=wx.getStorageSync(k)==='1';wx.removeStorageSync(k);return result(ok?EvidenceState.VERIFIED:EvidenceState.FAILED,'wx临时写读删闭环');},
 async probeStorageManager(){if(typeof navigator==='undefined'||!navigator.storage)return result(EvidenceState.UNSUPPORTED,'无StorageManager');const e=typeof navigator.storage.estimate==='function'?await navigator.storage.estimate():null;const p=typeof navigator.storage.persisted==='function'?await navigator.storage.persisted():null;return result(e||p!==null?EvidenceState.VERIFIED:EvidenceState.SURFACE,'存储管理状态真实返回',e&&Number.isFinite(e.quota)?`quota ${Math.round(e.quota/1024)}KB`:`persisted ${p}`);},
 async probeOpfs(){if(typeof navigator==='undefined'||!navigator.storage||typeof navigator.storage.getDirectory!=='function')return result(EvidenceState.UNSUPPORTED,'无OPFS入口');const r=await navigator.storage.getDirectory(),n='__aiui_diag__.txt',h=await r.getFileHandle(n,{create:true}),w=await h.createWritable();await w.write('ok');await w.close();const f=await h.getFile(),ok=f.size===2;await r.removeEntry(n);return result(ok?EvidenceState.VERIFIED:EvidenceState.FAILED,'临时文件写读删闭环',`${f.size} B`);}
};
</script>
<page><view class="screen"><view class="header"><text class="title">应用测试</text><text class="meta">能力基线 v{{version}} · {{pageText}}</text></view><view class="status"><text class="headline">{{headline}}</text><text class="summary">{{summary}}</text></view><view class="results"><view class="row" wx:for="{{visibleResults}}" wx:key="id"><text class="group">{{item.group}}</text><view class="main"><text class="label">{{item.label}}</text><text class="evidence">{{item.evidence}}{{item.metric ? ' · ' + item.metric : ''}}</text></view><text class="state state-{{item.state}}">{{item.stateLabel}}</text></view></view><view class="footer"><text>{{phase == 'running' ? '确认：停止' : phase == 'done' ? '确认：重试' : '确认：执行全部'}}</text><text>DEVICE DIAGNOSTIC · 自动翻页 · 非敏感证据</text></view></view></page>
<style>
.screen{position:relative;width:480px;height:352px;background:#000;color:#40ff5e;overflow:hidden;font-family:sans-serif}.header{position:absolute;left:14px;top:9px;width:452px;height:20px;display:flex;justify-content:space-between;align-items:center}.title{font-size:16px;font-weight:600}.meta{font-size:9px;opacity:.55;font-family:monospace}.status{position:absolute;left:14px;top:34px;width:452px;height:43px;display:flex;flex-direction:column;align-items:center;justify-content:center;border-bottom:1px solid rgba(64,255,94,.22)}.headline{font-size:17px;font-weight:600}.summary{font-size:10px;opacity:.7;margin-top:2px}.results{position:absolute;left:14px;top:83px;width:452px;height:232px;display:flex;flex-direction:column;gap:2px}.row{height:31px;display:flex;align-items:center;border-bottom:1px solid rgba(64,255,94,.12)}.group{width:58px;font-size:9px;opacity:.5}.main{width:310px;display:flex;flex-direction:column}.label{font-size:12px;font-weight:500}.evidence{font-size:8px;opacity:.58;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.state{width:72px;text-align:right;font-size:10px;font-family:monospace;opacity:.65}.state-verified{opacity:1;font-weight:600}.state-failed{opacity:1}.state-running{opacity:.85}.footer{position:absolute;left:14px;bottom:7px;width:452px;height:13px;display:flex;justify-content:space-between;font-size:9px;opacity:.55}
</style>
